### ISSUE TITLE
Generate an artifact in the CI for the pi3hat spine 

### ISSUE THREAD

**Issue by pgraverdy** [upkie/upkie#150]
When running the CI, build and save as an artifact the spine for pi3hat so that it can be used instead of recompiling each time locally.

**Comment by stephane-caron** [comment]
Let's use the artifact generated from #151 in the upcoming release :+1: 

As a future step, we could automate attaching artifacts to new releases (I will do it manually this time).

**Comment by stephane-caron** [comment]
Closing this issue as pi3hat spines are now attached automatically to new releases. Thanks @pgraverdy!
