### ISSUE TITLE
Observation dictionaries take too long to deserialise

### ISSUE THREAD

**Issue by boragokbakan** [upkie/upkie#180]
The `get_observation()` method of `SpineInterface` takes too long to deserialize the observation dictionaries (even longer when the observations are extended with additional fields) when run with `make run_xxx_balancer` (`make run_wheel_balancer` in my case, as I run an older version of `upkie`).

The profiling result from a quick run (2752 steps in 27.559 seconds) reveals that `get_observation()` takes around ~5 milliseconds (n.b. the method actually runs in ~3 milliseconds without the profiler) and that a method was called recursively `704472` times in [fallback.py](https://github.com/msgpack/msgpack-python/blob/main/msgpack/fallback.py) of `msgpack-python`. As the file name suggests, this is not the optimal "backend", as the default implementation is in Cython, and this pure-Python implementation only exists for compatibility reasons.

My first guess is that Bazel cannot pull the correct wheels (TBC), as the `msgpack-python` installed directly on the RasPi gives:

```
>>> import msgpack
>>> msgpack.Unpacker
<class 'msgpack._cmsgpack.Unpacker'>
```

whereas the Bazel one gives:
```
>>> import msgpack
>>> msgpack.Unpacker
<class 'msgpack.fallback.Unpacker'>
```

Profiling results (truncated):

| ncalls | tottime | percall | cumtime (↓) | percall |  filename:lineno(function) |
|-- | -- | -- | -- | -- | --
1 | 0.100 | 0.100 | 27.559 | 27.559 | main.py:43(run)
1 | 0.000 | 0.000 | 27.559 | 27.559 | <string>:1(<module>)
3/1 | 0.000 | 0.000 | 27.559 | 27.559 | {built-in method builtins.exec}
2752 | 0.025 | 0.000 | 13.914 | 0.005 | spine_interface.py:109(get_observation)
2752 | 0.067 | 0.000 | 10.107 | 0.004 | spine_interface.py:163(_read_dict)
5503 | 0.034 | 0.000 | 9.940 | 0.002 | fallback.py:623(__next__)
**704472/5503** | 3.144 | 0.000 | 9.894 | 0.002 | fallback.py:543(_unpack)
2750 | 0.116 | 0.000 | 8.981 | 0.003 | servo_controller.py:84(cycle)
704472 | 3.291 | 0.000 | 6.226 | 0.000 | fallback.py:441(_read_header)
2750 | 0.437 | 0.000 | 4.857 | 0.002 | contact_models.py:108(cycle)
8255 | 1.034 | 0.000 | 3.868 | 0.000 | spine_interface.py:183(_wait_for_spine)
2750 | 0.026 | 0.000 | 3.351 | 0.001 | spine_interface.py:134(set_action)
2751 | 0.039 | 0.000 | 3.200 | 0.001 | spine_interface.py:212(_write_dict)
101749/82499 | 0.624 | 0.000 | 3.184 | 0.000 | {built-in method numpy.core._multiarray_umath.implement_array_function}
2751 | 0.024 | 0.000 | 3.122 | 0.001 | fallback.py:881(pack)
294296/2751 | 1.409 | 0.000 | 3.095 | 0.001 | fallback.py:755(_pack)
2750 | 0.043 | 0.000 | 3.080 | 0.001 | _spectral_py.py:617(spectrogram)
33008/2751 | 0.377 | 0.000 | 3.033 | 0.001 | fallback.py:964(_pack_map_pairs)
2750 | 0.024 | 0.000 | 2.604 | 0.001 | contact_models.py:47(cycle)
747113 | 1.498 | 0.000 | 2.595 | 0.000 | spine_interface.py:156(_read_request)
2750 | 0.032 | 0.000 | 2.580 | 0.001 | contact_models.py:34(get_contact_probability)
2750 | 0.078 | 0.000 | 2.548 | 0.001 | _rgi.py:516(interpn)
2750 | 0.381 | 0.000 | 2.090 | 0.001 | _spectral_py.py:1634(_spectral_helper)
1276853 | 1.343 | 0.000 | 1.688 | 0.000 | fallback.py:407(_reserve)
327469 | 0.919 | 0.000 | 1.391 | 0.000 | fallback.py:399(_read)
2750 | 0.112 | 0.000 | 1.279 | 0.000 | wheel_controller.py:297(cycle)
2750 | 0.216 | 0.000 | 1.277 | 0.000 | _rgi.py:274(__call__)
2750 | 0.135 | 0.000 | 1.211 | 0.000 | _spectral_py.py:1928(_fft_helper)
2750 | 0.049 | 0.000 | 1.178 | 0.000 | rate_limiter.py:100(sleep)
2750 | 0.033 | 0.000 | 1.076 | 0.000 | __init__.py:2070(warning)
2750 | 0.024 | 0.000 | 1.042 | 0.000 | __init__.py:1444(warning)
2750 | 0.026 | 0.000 | 1.007 | 0.000 | __init__.py:1561(_log)
5500 | 0.048 | 0.000 | 0.965 | 0.000 | _spectral_py.py:1978(_triage_segments)
2750 | 0.014 | 0.000 | 0.907 | 0.000 | base_pitch.py:111(compute_base_pitch_from_imu)
5500 | 0.309 | 0.000 | 0.826 | 0.000 | _rgi.py:14(_check_points)
2750 | 0.070 | 0.000 | 0.814 | 0.000 | _windows.py:2261(get_window)
2750 | 0.538 | 0.000 | 0.742 | 0.000 | _windows.py:807(tukey)
5500 | 0.026 | 0.000 | 0.673 | 0.000 | <__array_function__ internals>:177(mean)
2750 | 0.011 | 0.000 | 0.648 | 0.000 | __init__.py:1587(handle)
2750 | 0.019 | 0.000 | 0.630 | 0.000 | __init__.py:1641(callHandlers)
5500 | 0.047 | 0.000 | 0.623 | 0.000 | fromnumeric.py:3345(mean)
2750 | 0.016 | 0.000 | 0.611 | 0.000 | __init__.py:935(handle)
11000/5500 | 0.027 | 0.000 | 0.595 | 0.000 | <__array_function__ internals>:177(roll)
27503 | 0.578 | 0.000 | 0.578 | 0.000 | {method 'reduce' of 'numpy.ufunc' objects}
5500 | 0.218 | 0.000 | 0.576 | 0.000 | _methods.py:164(_mean)
2750 | 0.024 | 0.000 | 0.571 | 0.000 | __init__.py:1067(emit)
2108203 | 0.566 | 0.000 | 0.566 | 0.000 | {built-in method builtins.len}
11000/5500 | 0.387 | 0.000 | 0.564 | 0.000 | numeric.py:1147(roll)
2750 | 0.072 | 0.000 | 0.538 | 0.000 | _rgi.py:364(_prepare_xi)
2750 | 0.015 | 0.000 | 0.510 | 0.000 | _spectral_py.py:1842(detrend_func)
2750 | 0.045 | 0.000 | 0.505 | 0.000 | _rgi.py:232(__init__)
2750 | 0.062 | 0.000 | 0.494 | 0.000 | _signaltools.py:3510(detrend)
11000 | 0.044 | 0.000 | 0.482 | 0.000 | <__array_function__ internals>:177(all)
16500 | 0.110 | 0.000 | 0.473 | 0.000 | fromnumeric.py:69(_wrapreduction)
1628403 | 0.469 | 0.000 | 0.469 | 0.000 | {built-in method builtins.isinstance}
2750 | 0.151 | 0.000 | 0.467 | 0.000 | base_pitch.py:76(compute_base_orientation_from_imu)
2750 | 0.183 | 0.000 | 0.426 | 0.000 | base_pitch.py:26(compute_pitch_frame_in_parent)
758119 | 0.415 | 0.000 | 0.415 | 0.000 | {method 'seek' of 'mmap.mmap' objects}
758120 | 0.399 | 0.000 | 0.399 | 0.000 | {method 'read' of 'mmap.mmap' objects}
2750 | 0.006 | 0.000 | 0.396 | 0.000 | _rgi.py:503(_find_indices)
2750 | 0.164 | 0.000 | 0.391 | 0.000 | {scipy.interpolate._rgi_cython.find_indices}
11000 | 0.053 | 0.000 | 0.388 | 0.000 | fromnumeric.py:2432(all)
2750 | 0.029 | 0.000 | 0.382 | 0.000 | _backend.py:17(__ua_function__)
143022 | 0.247 | 0.000 | 0.372 | 0.000 | fallback.py:970(_pack_raw_header)
2750 | 0.015 | 0.000 | 0.364 | 0.000 | __init__.py:912(format)
2750 | 0.042 | 0.000 | 0.349 | 0.000 | basic.py:40(r2c)
2750 | 0.033 | 0.000 | 0.349 | 0.000 | spdlog.py:48(format)
2750 | 0.313 | 0.000 | 0.324 | 0.000 | _rgi.py:506(_find_out_of_bounds)
749871 | 0.305 | 0.000 | 0.305 | 0.000 | {built-in method from_bytes}
327469 | 0.286 | 0.000 | 0.286 | 0.000 | {built-in method sys.intern}
8250 | 0.024 | 0.000 | 0.269 | 0.000 | <__array_function__ internals>:177(norm)
733355 | 0.261 | 0.000 | 0.261 | 0.000 | {built-in method time.perf_counter_ns}
2750 | 0.017 | 0.000 | 0.260 | 0.000 | __init__.py:1546(makeRecord)
2750 | 0.111 | 0.000 | 0.243 | 0.000 | __init__.py:278(__init__)
2750 | 0.034 | 0.000 | 0.231 | 0.000 | __init__.py:646(format)
5500 | 0.025 | 0.000 | 0.225 | 0.000 | <__array_function__ internals>:177(any)
8250 | 0.118 | 0.000 | 0.219 | 0.000 | linalg.py:2342(norm)
327469 | 0.214 | 0.000 | 0.214 | 0.000 | {method 'decode' of 'bytearray' objects}
2750 | 0.012 | 0.000 | 0.200 | 0.000 | <__array_function__ internals>:177(moveaxis)
244912 | 0.195 | 0.000 | 0.195 | 0.000 | {built-in method _struct.unpack_from}
294294 | 0.191 | 0.000 | 0.191 | 0.000 | {built-in method _struct.pack}
2749 | 0.124 | 0.000 | 0.185 | 0.000 | stride_tricks.py:38(as_strided)
2750 | 0.059 | 0.000 | 0.173 | 0.000 | numeric.py:1411(moveaxis)
5500 | 0.016 | 0.000 | 0.171 | 0.000 | <__array_function__ internals>:177(diag)
5500 | 0.025 | 0.000 | 0.163 | 0.000 | fromnumeric.py:2333(any)
437318 | 0.156 | 0.000 | 0.156 | 0.000 | {method 'write' of '_io.BytesIO' objects}
5500 | 0.018 | 0.000 | 0.156 | 0.000 | {method 'sum' of 'numpy.ndarray' objects}
2750 | 0.013 | 0.000 | 0.154 | 0.000 | <__array_function__ internals>:177(zeros_like)
11000 | 0.039 | 0.000 | 0.153 | 0.000 | <__array_function__ internals>:177(empty_like)
2852 | 0.150 | 0.000 | 0.150 | 0.000 | {method 'write' of '_io.TextIOWrapper' objects}
2750 | 0.058 | 0.000 | 0.145 | 0.000 | rotations.py:23(rotation_matrix_from_quaternion)
5500 | 0.008 | 0.000 | 0.138 | 0.000 | _methods.py:47(_sum)
11000 | 0.094 | 0.000 | 0.136 | 0.000 | numeric.py:1348(normalize_axis_tuple)
5500 | 0.084 | 0.000 | 0.136 | 0.000 | twodim_base.py:240(diag)
2750 | 0.134 | 0.000 | 0.134 | 0.000 | {built-in method scipy.fft._pocketfft.pypocketfft.r2c}
2750 | 0.016 | 0.000 | 0.132 | 0.000 | <__array_function__ internals>:177(cumsum)
5500 | 0.018 | 0.000 | 0.130 | 0.000 | fromnumeric.py:51(_wrapfunc)
2750 | 0.026 | 0.000 | 0.123 | 0.000 | numeric.py:77(zeros_like)
2750 | 0.011 | 0.000 | 0.122 | 0.000 | <__array_function__ internals>:177(diff)
2750 | 0.066 | 0.000 | 0.115 | 0.000 | wheel_controller.py:241(update_target_yaw_velocity)
5500 | 0.032 | 0.000 | 0.115 | 0.000 | <__array_function__ internals>:177(copyto)
2750 | 0.035 | 0.000 | 0.114 | 0.000 | __init__.py:578(formatTime)
33008 | 0.069 | 0.000 | 0.112 | 0.000 | fallback.py:955(_pack_map_header)
2750 | 0.013 | 0.000 | 0.104 | 0.000 | fromnumeric.py:2523(cumsum)
2750 | 0.093 | 0.000 | 0.099 | 0.000 | function_base.py:1320(diff)
2750 | 0.021 | 0.000 | 0.098 | 0.000 | numeric.py:150(ones)
2750 | 0.024 | 0.000 | 0.094 | 0.000 | wheel_controller.py:400(get_wheel_velocities)
2750 | 0.021 | 0.000 | 0.090 | 0.000 | _rgi.py:264(_check_fill_value)
5500 | 0.017 | 0.000 | 0.090 | 0.000 | <__array_function__ internals>:177(dot)
5500 | 0.089 | 0.000 | 0.089 | 0.000 | {built-in method scipy.interpolate.interpnd._ndim_coords_from_arrays}
46749 | 0.086 | 0.000 | 0.086 | 0.000 | {built-in method numpy.asarray}
5500 | 0.077 | 0.000 | 0.086 | 0.000 | _methods.py:67(_count_reduce_items)
5500 | 0.085 | 0.000 | 0.085 | 0.000 | contact_models.py:104(logistic)

**Comment by stephane-caron** [comment]
I'm not able to reproduce this issue. What commit of Vulp is your upkie repository using? (Located in ``tools/workspace/vulp/repository.bzl``.)

With an up-to-date version of Vulp the BUILD file uses the system ``msgpack`` on the raspi:

```python
    deps = select({
        # Selecting the right CPU architecture for the Raspberry Pi is
        # currently a tough nut to crack for Bazel. We only enable compiled
        # dependencies on the host side for now.
        # Followed in: https://github.com/upkie/upkie/issues/1
        "//:pi64_config": [],
        "//conditions:default": [
            requirement("msgpack"),
            requirement("posix_ipc"),
        ],
    }),
```

**Comment by stephane-caron** [comment]
Hmm, that version should have had the fix :thinking: I'm curious why you ended up with a fallback `msgpack` then (but as long as you made it work it's not so important).

Vulp v2.1.0 has a check for this now:

```python
def vulp_repository():
    """
    Clone repository from GitHub and make its targets available for binding.
    """
    git_repository(
        name = "vulp",
        remote = "https://github.com/upkie/vulp.git",
        commit = "6b547a55e100841fecda86dd094297a418c02f49",
        shallow_since = "1704302541 +0100",
    )
```
