### ISSUE TITLE
Bill of Materials Link Broken

### ISSUE THREAD

**Issue by Wyzard2025** [upkie/upkie#447]
## Bug description

The power distribution board link in the bill of materials is broken - leads to 404 error. 

## Expected behavior

Link leading to mjbots page: https://mjbots.com/products/mjbots-power-dist-r4-5b 

## Reproduction steps

1. Click mjbots link on mjbots power dist, r4.3b+	
2. See error

### Context

- Upkie version: most recent
- mjbots appears to have discontinued their sale of older versions of the power distribution board. 
- If applicable, screenshot to help explain the issue?
<img width="684" alt="image" src="https://github.com/user-attachments/assets/c3bb20cf-6aa5-4627-8a3c-1995d9d11b13">

<img width="959" alt="image" src="https://github.com/user-attachments/assets/e23a1cf9-2058-4117-a7d5-4eb6c6f0de15">

**Comment by stephane-caron** [comment]
Thanks a lot for this detailed report, the link is fixed now :+1:
