### ISSUE TITLE
For MacOs : Launching start_simulation.sh, error -v: unary operator expected

### ISSUE THREAD

**Issue by FEIPNG** [upkie/upkie#457]
## Bug description

Hello ! After well installed upkie with "conda install -c conda-forge upkie", when I tried to launch the command "./start_simulation.sh", there is the message error : "
macOS system
ARM architecture
start_simulation.sh: line 58: [: -v: unary operator expected
start_simulation.sh: line 90: [: -v: unary operator expected "

## Expected behavior

I tried to fix the problem by removing the condition " && [ ! -v BUILD ] " in the line 58. And now the command "./start_simulation.sh" worked, but I am not sure if there will have other problem by simply removing this and condition. I also tried the exemple like "balancing_state_feedback.py", and there is no problem for me now. So I think that maybe it is better to verify start_simulation.sh with MacOS Thanks !

## Reproduction steps

1. follow the install step : create conda environment and install the package "conda install -c conda-forge upkie"
2. launch the command "./start_simulation.sh"

### Context

- OS: [ macOS]
- Upkie version: [6.0.0]

**Comment by stephane-caron** [comment]
Thank you for reporting this issue :+1: It should be fixed now with 6be11d8cb0260b8969258a854f1f92ab75356c39 (you can `git pull` the repository to get the latest version). Feel free to re-open if you encounter any follow-up issue.

**Comment by anditp** [comment]
Hello! Following the same reproduction steps as above and in the same context, when I try running "start_simulation.sh" I get the following error message:
"
macOS system
ARM architecture
./start_simulation.sh: line 58: conditional binary operator expected
./start_simulation.sh: line 58: syntax error near `BUILD'
./start_simulation.sh: line 58: `if [[ -n "$SPINE_ARCHIVE" ]] && [[ ! -v BUILD ]]; then'
"

**Comment by stephane-caron** [comment]
Thank you, I had misidentified the problem in my previous commit. It should be fixed by https://github.com/upkie/upkie/pull/461 (thanks @ubgk for checking it on macOS :pray:).
