### ISSUE TITLE
Joystick not consistently detected

### ISSUE THREAD

**Issue by stephane-caron** [upkie/upkie#70]
An issue that happens with some USB joysticks: the joystick is successfully loaded in `/dev/input/js0` and we can see it (e.g. ``cat``ing that file), yet while the spine starts successfully, it doesn't receive any joystick observation.

**Comment by stephane-caron** [comment]
Closing as this has not happened for a long time.

**Comment by hyhan0118** [comment]
Hi Stéphane,
I’m running into an issue: I can see gamepad events at /dev/input/js0, but when running pink controller, Upkie doesn’t react the control input.
